### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by cugwu** [RistoranteRist/MandelbulbVariationsGenerator#1]
Hi, thanks for your amazing work. Is it possible to shear the pre-trained weights of resnet50 and wide_resnt50_2? Many thanks for considering my request.

**Comment by hyrodium** [comment]
Sorry for the late reply!
We have uploaded the weights to the following drive.
https://ristinc.sharepoint.com/:f:/g/EvJsm55kaBNKnVJkhA30PUUBP9ckZcVNNH3m0VF6rcqtKQ?e=fd9QZG

We will update the README with the url later.
